name: CI

on: [pull_request]

jobs:
  StyLua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v2
    - name: Run StyLua
      run: stylua --check .
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # For all versions see https://github.com/neovim/neovim/tags
          - neovim: 0.8.3
          - neovim: 0.9.4
    name: "Test with Neovim ${{ matrix.neovim }}"
    steps:
    - uses: actions/checkout@v4
    - name: "Set Neovim version to ${{ matrix.neovim}}"
      run: |
        sed -i '/neovim/c\neovim ${{ matrix.neovim }}' .tool-versions
        cat .tool-versions
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v2
    - name: Run tests
      run: ./tests/run.sh
